version: '3'
services:
  frontend:
    tty: true
    build:
      context: ../../note-taker-web
      dockerfile: Dockerfile
    networks:
      - default
    expose:
      - 7890
      - 7891
    ports:
      - 7890:7890
      - 7891:7891
    environment:
      - VITE_NOTE_TAKER_API_BASE_URL=http://note-taker-api.kawaiivee.xyz
    depends_on:
      - backend
  backend:
    tty: true
    build:
      context: ../../NoteTaker/NoteTaker
      dockerfile: Dockerfile
    networks:
      - default
    expose:
      - 7893
      - 7892
    ports:
      - 7893:7893
      - 7892:7892
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:7893;http://+:7892
    depends_on:
      - db
  db:
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: note_taker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kittycatmeow
networks:
  default:
    driver: bridge