version: '3'
services:
  frontend:
    container_name: note-taker-frontend
    build:
      context: ../../note-taker-web
      dockerfile: Dockerfile
    expose:
      - 7890
    ports:
      - 7890:7890
    environment:
      - VITE_NOTE_TAKER_API_BASE_URL=http://note-taker-api.kawaiivee.xyz
    depends_on:
      - backend
  backend:
    container_name: note-taker-backend
    build:
      context: ../../NoteTaker/NoteTaker
      dockerfile: Dockerfile
    expose:
      - 7892
    ports:
      - 7892:7892
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:7892
    depends_on:
      - db
  db:
    container_name: note-taker-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: note_taker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kittycatmeow