version: '3'
services:
  frontend:
    container_name: note-taker-frontend
    networks:
      - dev-network:
    tty: true
    build:
      context: ../../note-taker-web
      dockerfile: Dockerfile
    expose:
      - 7890
    ports:
      - "7890:7890"
    environment:
      - VITE_NOTE_TAKER_API_BASE_URL=http://note-taker-api.kawaiivee.xyz
    depends_on:
      - backend
  backend:
    container_name: note-taker-backend
    networks:
      - dev-network:
    tty: true
    build:
      context: ../../NoteTaker/NoteTaker
      dockerfile: Dockerfile
    expose:
      - 7892
    ports:
      - "7892:7892"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
  db:
    container_name: note-taker-db
    networks:
      - dev-network:
    image: postgres:latest
    expose:
      - 5432
      - 7894
    ports:
      - "7894:5432"
    environment:
      POSTGRES_DB: note_taker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kittycatmeow
networks:
  dev-network:
    external: true