version: '3'
services:
  note-taker-frontend:
    container_name: note-taker-frontend
    networks:
      - note-taker-network
    tty: true
    build:
      context: ../../note-taker-web
      dockerfile: Dockerfile
    ports:
      - "7890:7890"
    environment:
      - VITE_NOTE_TAKER_API_BASE_URL=http://note-taker-api.kawaiivee.xyz
    depends_on:
      - note-taker-backend
  note-taker-backend:
    container_name: note-taker-backend
    networks:
      - note-taker-network
    tty: true
    build:
      context: ../../NoteTaker/NoteTaker
      dockerfile: Dockerfile
    ports:
      - "7892:7892"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - note-taker-db
  note-taker-db:
    container_name: note-taker-db
    networks:
      - note-taker-network
    image: postgres:latest
    ports:
      - "7894:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: note_taker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kittycatmeow
networks:
  note-taker-network:
    - bridge