version: '3'
services:
  frontend:
    container_name: note-taker-frontend
    tty: true
    build:
      context: ../../note-taker-web
      dockerfile: Dockerfile
    ports:
      - "7890:7890"
    environment:
      - VITE_NOTE_TAKER_API_BASE_URL=http://note-taker-api.kawaiivee.xyz
    depends_on:
      - backend
  backend:
    container_name: note-taker-backend
    tty: true
    build:
      context: ../../NoteTaker/NoteTaker
      dockerfile: Dockerfile
    ports:
      - "7892:7892"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
    command: sh -c "dotnet restore && dotnet tool install --global dotnet-ef && cd ../../NoteTaker/NoteTaker && dotnet ef database update"
  db:
    container_name: note-taker-db
    image: postgres:latest
    ports:
      - "7894:5432"
    environment:
      POSTGRES_DB: note_taker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kittycatmeow